config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote
    end
  end

  root 'candidates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :vote_logs, dependent: :destroy
  validates :name, presence: true
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]

  def index
    @candidates = Candidate.all
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to root_path, notice: '新增候選人成功'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @candidate.update(candidate_params)
      redirect_to root_path, notice: '資料更新成功'
    else
      render :edit
    end
  end

  def destroy
    if @candidate.destroy
      redirect_to root_path, notice: '刪除成功'
    end
  end

  def vote
    @candidate.vote_logs.create(ip_address: request.remote_ip) if @candidate
    redirect_to root_path, notice: '投票完成'
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :age, :party, :politics)
  end

  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>

<ul>
  <% candidate.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<% end %>

<%= form_for candidate do |f| %>
  <div>
    <%= f.label :name, '姓名' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :age, '年齡' %>
    <%= f.text_field :age %>
  </div>

  <div>
    <%= f.label :party, '黨派' %>
    <%= f.text_field :party %>
  </div>

  <div>
    <%= f.label :politics, '政見' %>
    <%= f.text_area :politics %>
  </div>

  <%= f.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render 'form', candidate: @candidate %>

<br/>
<%= link_to '回候選人列表', root_path %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= link_to '新增候選人', new_candidate_path %>

<table class='table'>
  <thead>
    <tr>
      <td>投票</td>
      <td>候選人姓名</td>
      <td>年齡</td>
      <td>黨派</td>
      <td>政見</td>
      <td>得票數</td>
      <td>其他設定</td>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to '投給這位', vote_candidate_path(candidate), method: 'post', data: { confirm: '確定投給這位嗎？'}, class: "btn btn-danger" %></td>
      <td><%= link_to candidate.name, candidate_path(candidate) %></td>
      <td><%= candidate.age %></td>
      <td><%= candidate.party %></td>
      <td><%= candidate.politics %></td>
      <td><%= candidate.vote_logs.size %></td>
      <td>
        <%= link_to '編輯', edit_candidate_path(candidate), class: "btn btn-primary" %>
        <%= link_to '刪除', candidate_path(candidate), method: 'delete', data: { confirm: '確定刪除嗎？' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= form_for @candidate do |f| %>
  <div>
    <%= f.label :name, '姓名' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :age, '年齡' %>
    <%= f.text_field :age %>
  </div>

  <div>
    <%= f.label :party, '黨派' %>
    <%= f.text_field :party %>
  </div>

  <div>
    <%= f.label :politics, '政見' %>
    <%= f.text_area :politics %>
  </div>

  <%= f.submit '新增' %>
<% end %>

<br/>
<%= link_to '回候選人列表', root_path %>

app/views/candidates/show.html.erb
<% if @candidate %>

  <h1><%= @candidate.name %></h1>

  <ul>
    <li>年齡: <%= @candidate.age %></li>
    <li>黨派: <%= @candidate.party %></li>
    <li>政見: <%= @candidate.politics %></li>
  </ul>

<% else %>

  <h1>無此資料</h1>

<% end %>

<%= link_to '回候選人列表', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>